Update to Tutorial 04 (#5)

diff --git a/.github/workflows/deploy-infrastructure-tutorial-04.yml b/.github/workflows/deploy-infrastructure-tutorial-04.yml
--- a/.github/workflows/deploy-infrastructure-tutorial-04.yml
+++ b/.github/workflows/deploy-infrastructure-tutorial-04.yml
@@ -12,51 +12,81 @@ permissions:
   contents: read   ## Need to be able to read what it creates (i.e., read what was retrieved from Azure AD)
 
 env:
+    ENVIRONMENT_NAME_PREFIX: Tutorial-04
     AZURE_RESOURCEGROUP_NAME: Xyz-Tutorial-04
-    ENVIRONMENT_TYPE: nonprod
     DEPLOYMENT_NAME: "GitHub-Workflow-Run-${{ github.run_number }}" ## Alphanumeric plus .-_ (i.e., `[a-zA-Z0-9.-_]+`)
     PATH_TO_BICEP_FILE: ./deploy/main-tutorial-04.bicep
 
 jobs:
 
-  # Lint the Bicep file.
-  lint:
-    uses: ./.github/workflows/job-lint-bicep.yml
-    with:
-      pathToBicepFile: ${{ env.AZURE_RESOURCEGROUP_NAME }}
+  ## Workaround to pass non-secret env vars to jobs
+  setup_vars: 
+    runs-on: ubuntu-latest
+    # Map step output to a job output
+    outputs:
+      AZURE_RESOURCEGROUP_NAME: ${{ steps.step1.outputs.AZURE_RESOURCEGROUP_NAME }}
+      DEPLOYMENT_NAME: ${{ steps.step1.outputs.DEPLOYMENT_NAME }}
+      ENVIRONMENT_NAME_PREFIX: ${{ steps.step1.outputs.ENVIRONMENT_NAME_PREFIX }}
+      PATH_TO_BICEP_FILE: ${{ steps.step1.outputs.PATH_TO_BICEP_FILE }}
+    steps:
+      - run: echo ${{ env.PATH_TO_BICEP_FILE }}
+      - name: Set Variables
+        id: step1
+        run: |
+          echo "AZURE_RESOURCEGROUP_NAME=${{ env.AZURE_RESOURCEGROUP_NAME }}" >> $GITHUB_OUTPUT
+          echo "DEPLOYMENT_NAME=${{ env.DEPLOYMENT_NAME }}" >> $GITHUB_OUTPUT
+          echo "ENVIRONMENT_NAME_PREFIX=${{ env.ENVIRONMENT_NAME_PREFIX }}" >> $GITHUB_OUTPUT
+          echo "PATH_TO_BICEP_FILE=${{ env.PATH_TO_BICEP_FILE }}" >> $GITHUB_OUTPUT
+      - name: Output Variables
+        run: |
+          echo ${{ steps.step1.outputs.AZURE_RESOURCEGROUP_NAME }}
+          echo ${{ steps.step1.outputs.DEPLOYMENT_NAME }}
+          echo ${{ steps.step1.outputs.ENVIRONMENT_NAME_PREFIX }}
+          echo ${{ steps.step1.outputs.PATH_TO_BICEP_FILE }}
 
-  validate:
-    # needs: [lint]
-    uses: ./.github/workflows/job-validate-bicep.yml
-    with:
-      pathToBicepFile: ./deploy/main-tutorial-04.bicep
-      environmentType: nonprod
-      resourceGroupName: Xyz-Tutorial-04
-    secrets:
-      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TUTORIAL_04 }}
-      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  ## Fail workflow if error in specifying variables above (i.e., if they're empty string)
+  ## Note: Deliberately a separate job, to validate that variable content is available via job outputs
+  test_var_availability:
+    needs: [setup_vars]
+    runs-on: ubuntu-latest
+    strategy:
+      matrix: 
+        variableName : 
+        - AZURE_RESOURCEGROUP_NAME
+        - DEPLOYMENT_NAME
+        - ENVIRONMENT_NAME_PREFIX
+        - PATH_TO_BICEP_FILE
+    steps:
+      - name: Variable is set and available via job outputs - needs.setup_vars.outputs.${{ matrix.variableName }}
+        shell: bash
+        run: |
+          if [ "${{ needs.setup_vars.outputs[format('{0}', matrix.variableName)] }}" != '' ]; then
+            echo "${{ matrix.variableName }} is set";
+          else
+            echo >&2 "${{ matrix.variableName }} unavailable";
+            exit 1
+          fi
 
-  preview:
-    needs: [lint, validate]
-    uses: ./.github/workflows/job-preview-bicep.yml
-    with:
-      pathToBicepFile: ./deploy/main-tutorial-04.bicep
-      environmentType: nonprod
-      resourceGroupName: Xyz-Tutorial-04
-    secrets:
-      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TUTORIAL_04 }}
-      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
   deploy:
-    needs: [preview]
-    uses: ./.github/workflows/job-deploy.yml
+    name: deploy to ${{ matrix.environmentType }}
+    needs: [setup_vars, test_var_availability]
+    uses: ./.github/workflows/job-deploy-to-environment.yml
+    strategy:
+      ## Run once for each permutation of matrix options - i.e., once per environment
+      ## - Parallelism limit allows for sequential deployments
+      ## - Fail fast cancels remaining matrix options if any other option fails/errors
+      matrix: 
+        environmentType: 
+        - nonprod
+        - prod
+      max-parallel: 1
+      fail-fast: true
     with:
-      pathToBicepFile: ./deploy/main-tutorial-04.bicep
-      environmentNamePrefix: Tutorial-04
-      environmentType: nonprod
-      resourceGroupName: Xyz-Tutorial-04
+      pathToBicepFile: ${{ needs.setup_vars.outputs.PATH_TO_BICEP_FILE }}
+      environmentNamePrefix: ${{ needs.setup_vars.outputs.ENVIRONMENT_NAME_PREFIX}}
+      environmentType: ${{ matrix.environmentType }}
+      resourceGroupName: ${{ needs.setup_vars.outputs.AZURE_RESOURCEGROUP_NAME}}-${{ matrix.environmentType }}
     secrets:
       AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TUTORIAL_04 }}
       AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
